title = "yuudee's blog"
baseURL = 'https://yuudee.net/'

# This is what goes in <html lang="">
languageCode = 'japanese'

# This defines how dates are formatted
defaultContentLanguage = "japanese"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

# traditional way: theme component resides in directory 'themes'
theme = "hugo-blog-awesome"

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

############################## japanese language ################################
[Languages.japanese]
  languageName = "Japanese"
  languageCode = "japanese"
  contentDir = "content/"
  weight = 1

  [Languages.japanese.menu]
  [[Languages.japanese.menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.japanese.menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[Languages.japanese.menu.main]]
    pageRef="about"
    name = 'About'
    url = '/pages/about/'
    weight = 30
  [[Languages.japanese.menu.main]]
    pageRef="book"
    name = 'Book'
    url = '/pages/book/'
    weight = 30

[Languages.japanese.params]
  sitename = "yuudee's blog"
  defaultColor = "light" # set color mode: dark, light, auto

  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
  # the default value is set to 'auto'.
  # You can take a look at layouts/index.html for more information.
  description = "Minimal Hugo blog theme with light and dark mode support"
  mainSections = ['posts']
  goToTop = true # set to false to disable 'go to top' button
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
  # Your custom scripts will be concatenated to one file `custom.js`.
  # When building for production it will be minified.
  # The file `custom.js` is loaded on each page (before body tag ends).
  dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
  # See https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for available date formats.
  rssFeedDescription = "summary" # available options: 1) summary 2) full
  # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
  # full - includes full blog post in the RSS feed. Generated using Hugo .Content .
  # By default (or if nothing is specified), summary is used.

[Languages.japanese.params.author]
  avatar = "howl012.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "yuudee's blog"
  name = "yuudee "
  description = "備忘録を兼ねた技術ブログ？のようなものです．誰かの参考になれば幸いです．"

# Allow to override webmanifest options
[Languages.japanese.params.webmanifest]
  name = "sitename" # will use "params.sitename" or "title" by default
  short_name = "sitename" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"

# Allow to override `browserconfig.xml` params (configuration for windows embedded browsers)
[params.browserconfig]
  TileColor = "#2d89ef" # default windows 10 blue tile color

[[params.socialIcons]]
name = "github"
url = "https://github.com/yuudee"

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/yuu__dee"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"

[params]
  toc = false # set to false to disable table of contents 'globally'
  tocOpen = true # set to true to open table of contents by default
  math = true