name: Deploy Hugo site to VPS

on:
  push:
    branches:
      - main  # デプロイをトリガーするブランチ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.133.1'

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Build the site
      run: hugo --minify

    - name: Deploy to VPS
      run: |
        rsync -avz --delete docs/ username@your_vps_ip:/path/to/your/web/directory
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
